project:
    id: 661a6e16-d93a-5d57-a289-419091c391dc
session:
    idle_timeout_seconds: 600
build:
    framework: ios
    profiles:
        development:
            ios:
                app_id: 766a0fe0-48e1-4341-9164-f51b2f0b0dfe
                build_commands:
                    - xcodebuild -project SwiftMinimal.xcodeproj -scheme SwiftMinimal -configuration Debug -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' -derivedDataPath build CODE_SIGNING_ALLOWED=NO build
                output_path: build/Build/Products/Debug-iphonesimulator/*.app
        pr-review:
            ios:
                app_id: 766a0fe0-48e1-4341-9164-f51b2f0b0dfe
                build_commands:
                    - xcodebuild -project SwiftMinimal.xcodeproj -scheme SwiftMinimal -configuration Debug -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' -derivedDataPath build CODE_SIGNING_ALLOWED=NO build
                output_path: build/Build/Products/Debug-iphonesimulator/*.app
pr_review:
    enabled: true
    review_triggers:
        drafts: false
    build:
        kind: revyl
        profile: pr-review
    proof_of_changes:
        enabled: true
        harness:
            kind: revyl
    strict_ci_check:
        build: true
